### ISSUE TITLE
Bug: Google Blocks Access to Interface from Social Media Apps

### ISSUE THREAD

**Issue by yanirmr** [yairl/ivrit.ai#23]
### Bug Description
When users try to navigate to the ivrit.ai interface from within social media applications such as LinkedIn, Twitter, and Facebook, they encounter a Google block error. An example of the error message is attached as an image with this issue.

### Steps to Reproduce
1. Open LinkedIn, Twitter, or Facebook app.
2. Try to follow a link to the [serve.ivrit.ai ](https://serve.ivrit.ai/).
3. Observe the error message from Google stating that the user agent is disallowed (403).

### Expected Behavior
The link should open the ivrit.ai interface without any blocks, allowing users to interact with the service as intended.

### Screenshots
![image](https://github.com/yairl/ivrit.ai/assets/22538302/bc47c8ac-aca5-47fb-8b6e-457b0dbc6888)

### Possible Cause
This could be related to the `robots.txt` file or other server configuration that specifies how Googlebot and other user agents should interact with the site, potentially blocking certain user agents unintentionally.

### Suggested Next Steps
- Review server settings and the `robots.txt` file to ensure that there are no rules that would block legitimate user agents.
- Verify if the issue is with the configuration on Google's side or with the way the links are being shared on social media platforms.
- It may also be helpful to check the server logs to see if there are any additional details about the requests that are being blocked.

We need to resolve this to ensure users have seamless access to ivrit.ai regardless of where they're coming from.

Thank you for looking into this issue.

**Comment by yairl** [comment]
I investigated this to the best of my ability.

Per my current understanding, as the native application is not under our control (example: LinkedIn app), possible solutions such as opening the link in a web browser application, or having it the application masquerade as a different browser is not possible (at least not under Google's guidelines).

For now, I'm unfortunately closing this issue as Won't Be Fixed. 😞 
If you or others have specific suggestions about how to resolve this, please reopen and we'll give it another shot.
