### ISSUE TITLE
Provide uniquely-identifying ID (using segment index or otherwise) in transcription screen

### ISSUE THREAD

**Issue by yairl** [yairl/ivrit.ai#4]
Request is to have a clear, unique ID (or several fields that form a single unique ID), so that transcribers can report issues with specific segments when needed.

**Comment by yairl** [comment]
Reported by @EvelinAlter.

**Comment by EvelinAlter** [comment]
hey @yairl should I be able to see it already in the UI?

**Comment by yairl** [comment]
I just enabled the new version - you should see now. :)
